# Generated by Django 5.0 on 2023-12-30 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hot_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
            preserve_default=False,
        ),
    ]
