export const assets = `${process.env.PUBLIC_URL}/assets`;

export function displayCard(data, limit, prop = (data, j) => data && j) {
  let condition;
  let cards = [];
  let i = 0,
    j = 0;
  while (i < limit && j < data.length) {
    condition = prop(data, j);
    if (condition) {
      cards[cards.length] = data[j];
      i++;
    }
    j++;
  }
  return cards;
}

export const imgs = [
  {
    name: "Manto",
    quantity: 86,
    ribbon: "HOT",
    image: "6.JPG",
    type: "Hair",
    category: ["Deep Curls"],
    best_seller: true,
    hot_seller: true,
    price: 200000,
    video: "https://gmail.com/",
    sold: false,
    likes: 32,
  },
  {
    name: "Pants",
    quantity: 200,
    ribbon: "HOT",
    image: "7.JPG",
    type: "Hair",
    category: ["Bonestraight"],
    best_seller: true,
    hot_seller: true,
    price: 18000,
    video: null,
    sold: false,
    likes: 21,
  },
  {
    name: "Coat",
    quantity: 520,
    ribbon: "SALE",
    image: "8.JPG",
    type: "Hair",
    category: ["Straight Wig"],
    best_seller: true,
    hot_seller: true,
    price: 20000,
    video: null,
    sold: false,
    likes: 86,
  },
  {
    name: "Shirt",
    quantity: 320,
    ribbon: "HOT",
    image: "9.JPG",
    type: "Hair",
    category: ["Pixie Curls"],
    best_seller: true,
    hot_seller: false,
    price: 19000,
    video: null,
    sold: false,
    likes: 46,
  },
  {
    name: "Jacket",
    quantity: 103,
    ribbon: null,
    image: "10.JPG",
    type: "Hair",
    category: ["Short Bob"],
    best_seller: false,
    hot_seller: true,
    price: 34500,
    video: null,
    sold: false,
    likes: 5,
  },
  {
    name: "Hoodie",
    quantity: 13,
    ribbon: "SALE",
    image: "11.JPG",
    type: "Hair",
    category: ["Pixie Curls"],
    best_seller: false,
    hot_seller: false,
    price: 345000,
    video: null,
    sold: false,
    likes: 5,
  },
  {
    name: "Hoodie",
    quantity: 13,
    ribbon: null,
    image: "1.JPG",
    type: "Hair",
    category: ["Bonestraight"],
    best_seller: true,
    hot_seller: true,
    price: 345000,
    video: null,
    sold: false,
    likes: 5,
  },
  {
    name: "Hoodie",
    quantity: 13,
    ribbon: null,
    image: "2.JPG",
    type: "Hair",
    category: ["Bonestraight"],
    best_seller: false,
    hot_seller: false,
    price: 345000,
    video: null,
    sold: false,
    likes: 5,
  },
  {
    name: "Hoodie",
    quantity: 13,
    ribbon: null,
    image: "3.JPG",
    type: "Hair",
    category: ["Bonestraight"],
    best_seller: false,
    hot_seller: false,
    price: 345000,
    video: null,
    sold: false,
    likes: 5,
  },
  {
    name: "Hoodie",
    quantity: 13,
    ribbon: null,
    image: "4.JPG",
    type: "Hair",
    category: ["Bonestraight"],
    best_seller: false,
    hot_seller: false,
    price: 345000,
    video: null,
    sold: false,
    likes: 5,
  },
  {
    name: "Hoodie",
    quantity: 13,
    ribbon: null,
    image: "5.JPG",
    type: "Hair",
    category: ["Bonestraight"],
    best_seller: false,
    hot_seller: false,
    price: 345000,
    video: null,
    sold: false,
    likes: 5,
  },
  {
    name: "Hoodie",
    quantity: 13,
    ribbon: null,
    image: "12.JPG",
    type: "Hair",
    category: ["Bonestraight"],
    best_seller: false,
    hot_seller: false,
    price: 345000,
    video: null,
    sold: false,
    likes: 5,
  },
  {
    name: "Hoodie",
    quantity: 13,
    ribbon: null,
    image: "13.JPG",
    type: "Hair",
    category: ["Bonestraight"],
    best_seller: false,
    hot_seller: false,
    price: 345000,
    video: null,
    sold: false,
    likes: 5,
  },
  {
    name: "Hoodie",
    quantity: 13,
    ribbon: null,
    image: "14.JPG",
    type: "Hair",
    category: ["Bonestraight"],
    best_seller: false,
    hot_seller: false,
    price: 345000,
    video: null,
    sold: false,
    likes: 5,
  },
];
